---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - etcpihole:/etc/pihole
      - dnsmasqd:/etc/dnsmasq.d
    networks:
      - homelab
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole-http.rule=Host(`pihole.${SITE}`)
      - traefik.http.routers.pihole-http.entrypoints=web
      - traefik.http.services.pihole.loadbalancer.server.port=80


volumes:
  etcpihole:
  dnsmasqd:

networks:
  homelab:
    external: true
